Add function for quickly handling static images

diff --git a/scripts_linux/script_v3/core-hybrid b/scripts_linux/script_v3/core-hybrid
--- a/scripts_linux/script_v3/core-hybrid
+++ b/scripts_linux/script_v3/core-hybrid
@@ -71,7 +71,19 @@ fi
 
 printf "Working on file $thefile \nTotal Frames $FRAMES at rate $_FPS , hence total duration $DURATION s\n"
 
-dothis () {
+convert_any () {
+  if [ $FRAMES -eq 1 ]; then
+    SIZELIMIT=299 # Limit for Signal stickers
+    # SIZELIMIT=99 # Limit for WhatsApp static stickers
+    convert_static
+  else
+    SIZELIMIT=299 # Limit for Signal stickers
+    # SIZELIMIT=499 # Limit for WhatsApp animated stickers
+    convert_animated
+  fi
+}
+
+convert_animated () {
   rm -rf $thedir/output*
   DEFAULTR="$RES"x"$RES"
   rm -rf $thedir/frame 
@@ -92,9 +104,9 @@ dothis () {
     done
     wait
 
-    ffmpeg -r $_FPS -i "$thedir/frame/%d.png" -vcodec apng -pix_fmt rgba -vf "scale=$RES:-1:flags=neighbor:sws_dither=none" -vf "scale=$RES:$RES:force_original_aspect_ratio=decrease,pad=$RES:$RES:(ow-iw)/2:(oh-ih)/2:color=black@0,setsar=1" -r $GFRAMES -plays 0 "$thedir/output.apng" &>/dev/null
+    ffmpeg -r $_FPS -y -i "$thedir/frame/%d.png" -vcodec apng -pix_fmt rgba -vf "scale=$RES:-1:flags=neighbor:sws_dither=none,scale=$RES:$RES:force_original_aspect_ratio=decrease,pad=$RES:$RES:(ow-iw)/2:(oh-ih)/2:color=black@0,setsar=1" -r $GFRAMES -plays 0 "$thedir/output.apng" &>/dev/null
   else
-    ffmpeg -i $thefile -vcodec apng -f apng -pix_fmt rgba -vf "scale=$RES:-1:flags=neighbor:sws_dither=none" -vf "scale=$RES:$RES:force_original_aspect_ratio=decrease,pad=$RES:$RES:(ow-iw)/2:(oh-ih)/2:color=black@0,setsar=1" -r $GFRAMES -plays 0 "$thedir/output.apng" &>/dev/null
+    ffmpeg -y -i $thefile -vcodec apng -f apng -pix_fmt rgba -vf "scale=$RES:-1:flags=neighbor:sws_dither=none,scale=$RES:$RES:force_original_aspect_ratio=decrease,pad=$RES:$RES:(ow-iw)/2:(oh-ih)/2:color=black@0,setsar=1" -r $GFRAMES -plays 0 "$thedir/output.apng" &>/dev/null
   fi
 
 
@@ -148,10 +160,44 @@ dothis () {
   #echo Putting delay for each at $delayatend 
   #echo Completed optimiation !
   testf=$(uuidgen)".png"
-  apngasm -F -d $delayatend -o $testf  $thedir/final/* > /dev/null 
+  apngasm -F -d $delayatend -o $testf  $thedir/final/* > /dev/null
 
+  checksize
+}
+
+convert_static () {
+  rm -rf $thedir/output*
+  DEFAULTR="$RES"x"$RES"
+  rm -rf $thedir/frame 
+  mkdir $thedir/frame
+  #echo $RES
+  #echo $DEFAULTR
+  echo "Working at $RES in $thefile"
+
+  if [[ $thefile == *.tgs ]]; then
+    tgs2png -s $(( $RES*4 ))x0 -o 1 -n 1 "$thedir/$thefile.json"  > "$thedir/frame/1.png"
+    ffmpeg -r 1 -y -i "$thedir/frame/1.png" -vcodec apng -pix_fmt rgba -vf "scale=$RES:-1:flags=neighbor:sws_dither=none,scale=$RES:$RES:force_original_aspect_ratio=decrease,pad=$RES:$RES:(ow-iw)/2:(oh-ih)/2:color=black@0,setsar=1" "$thedir/output.apng"
+  else
+    ffmpeg -y -i $thefile -vcodec apng -pix_fmt rgba -vf "scale=$RES:-1:flags=neighbor:sws_dither=none,scale=$RES:$RES:force_original_aspect_ratio=decrease,pad=$RES:$RES:(ow-iw)/2:(oh-ih)/2:color=black@0,setsar=1" "$thedir/output.apng"
+  fi
+  mv "$thedir/output.apng" "$thedir/output.png"
+
+  testf=$(uuidgen)".png"
+
+  pngnq-s9 -L -Qn -T15 -n90 -e '.1.png' "$thedir/output.png"
+
+  pngquant --nofs --quality 0-85 --strip --ext '.2.png' "$thedir/output.1.png"
+
+  optipng -o4 "$thedir/output.1.2.png" > /dev/null 2>&1
+
+  convert -quality 85 "$thedir/output.1.2.png" $testf > /dev/null  2>&1
+
+  checksize
+}
+
+checksize () {
   a=$(du $testf | sed -e "s/\s.*png//")
-  if [ $a -gt "299" ]; then
+  if [ $a -gt $SIZELIMIT ]; then
     if [[ $FILE == "" ]]; then
       if [[ $RES == "225" ]]; then
         if [[ $GFRAMES -gt "3" ]]; then
@@ -159,7 +205,7 @@ dothis () {
             rm -rf $thedir/output*
             rm -rf $testf
             echo "Forced to lower frame rate=$GFRAMES otherwise quality would suffer check $thefile !"
-            dothis
+            convert_any
             exit
           else
             printf "Can't do it with lowest resolution quality and WITH frame rate of $GFRAMES check $thefile "
@@ -172,7 +218,7 @@ dothis () {
       # printf "\n"
       goneu="x"
       todo
-      dothis
+      convert_any
       return 0
     else
       mv $FILE result/$(echo $thefile | sed "s/tgs/png/g;s/webm/png/g;s/webp/png/g")
@@ -195,7 +241,7 @@ dothis () {
         doframeup=1 
       fi
       todo
-      dothis 
+      convert_any
     else
       rm $FILE 
       FILE=$testf
@@ -209,10 +255,11 @@ dothis () {
       else
         rm -rf $thedir/output*
         todo
-        dothis 
+        convert_any
       fi
     fi
   fi
 }
-dothis 
-#dothis "225" "225x225" || dothis "512" "512x512" || dothis "400" "400x400" || dothis "350" "350x350" || dothis "300" "300x300"  || dothis "275" "275x275" || dothis "250" "250x250" ||  echo "File $thefile has been failed to be made smaller"
+
+convert_any
+#convert_any "225" "225x225" || convert_animated "512" "512x512" || convert_animated "400" "400x400" || convert_animated "350" "350x350" || convert_animated "300" "300x300"  || convert_animated "275" "275x275" || convert_animated "250" "250x250" ||  echo "File $thefile has been failed to be made smaller"
